export const client = {
  name: "Green Valley Landscaping",
  tagline: "Professional landscaping services in Irvine",
  phone: "(949) 123-4567",
  email: "john@greenvalley.com",
  address: "123 Main St.",
  city: "Irvine",
  state: "CA",
  serviceArea: ["Irvine"],
  primaryColor: "#2d5a3d",
  industry: "landscaping",
  services: ["Lawn care","Garden design","Irrigation","Tree trimming","Mulching","Sod installation","Leaf removal","Snow removal"],
  cmsUrl: "https://cms.sebvia.com",
  tenantSlug: "green-valley-landscaping",
  googleAnalyticsId: '',
  domain: "greenvalley.sebvia.com",
};
